import type { CatalogModelSpec } from './types';

export const DOMESTIC_MODELS: Record<string, CatalogModelSpec> = {
  // Qwen (Alibaba)
  'qwen-2.5-72b-instruct': {
    id: 'qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'qwen',
  },
  'qwen-2.5-32b-instruct': {
    id: 'qwen-2.5-32b-instruct',
    name: 'Qwen 2.5 32B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'qwen',
  },
  'qwen-2.5-coder-32b-instruct': {
    id: 'qwen-2.5-coder-32b-instruct',
    name: 'Qwen 2.5 Coder 32B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'qwen',
  },
  'qwen-2.5-vl-72b-instruct': {
    id: 'qwen-2.5-vl-72b-instruct',
    name: 'Qwen 2.5 VL 72B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'qwen',
  },
  'qwen-max': {
    id: 'qwen-max',
    name: 'Qwen Max',
    contextWindow: 32_768,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'qwen',
  },
  'qwen-plus': {
    id: 'qwen-plus',
    name: 'Qwen Plus',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'qwen',
  },
  'qwen-turbo': {
    id: 'qwen-turbo',
    name: 'Qwen Turbo',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'qwen',
  },
  'qwq-32b': {
    id: 'qwq-32b',
    name: 'QwQ 32B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: true, tools: true },
    ownedBy: 'qwen',
  },

  // Moonshot Kimi
  'moonshot-v1-8k': {
    id: 'moonshot-v1-8k',
    name: 'Kimi 8K',
    contextWindow: 8_192,
    maxOutputTokens: 4_096,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'moonshot',
  },
  'moonshot-v1-32k': {
    id: 'moonshot-v1-32k',
    name: 'Kimi 32K',
    contextWindow: 32_768,
    maxOutputTokens: 4_096,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'moonshot',
  },
  'moonshot-v1-128k': {
    id: 'moonshot-v1-128k',
    name: 'Kimi 128K',
    contextWindow: 131_072,
    maxOutputTokens: 4_096,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'moonshot',
  },
  'kimi-k1.5': {
    id: 'kimi-k1.5',
    name: 'Kimi K1.5',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'moonshot',
  },

  // Zhipu GLM
  'glm-4-plus': {
    id: 'glm-4-plus',
    name: 'GLM-4 Plus',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'zhipu',
  },
  'glm-4v-plus': {
    id: 'glm-4v-plus',
    name: 'GLM-4V Plus',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'zhipu',
  },
  'glm-zero-preview': {
    id: 'glm-zero-preview',
    name: 'GLM Zero',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: true, tools: true },
    ownedBy: 'zhipu',
  },
};
