import type { CatalogModelSpec } from './types';

export const OPENAI_MODELS: Record<string, CatalogModelSpec> = {
  'gpt-4o': {
    id: 'gpt-4o',
    name: 'GPT-4o',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'openai',
  },
  'gpt-4o-mini': {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'openai',
  },
  'gpt-4-turbo': {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'openai',
  },
  'gpt-4.5-preview': {
    id: 'gpt-4.5-preview',
    name: 'GPT-4.5 Preview',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'openai',
  },
  o1: {
    id: 'o1',
    name: 'o1',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'openai',
  },
  'o1-preview': {
    id: 'o1-preview',
    name: 'o1 Preview',
    contextWindow: 128_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: false, thinking: true, tools: false },
    ownedBy: 'openai',
  },
  'o1-mini': {
    id: 'o1-mini',
    name: 'o1 Mini',
    contextWindow: 128_000,
    maxOutputTokens: 65_536,
    capabilities: { vision: false, thinking: true, tools: false },
    ownedBy: 'openai',
  },
  o3: {
    id: 'o3',
    name: 'o3',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'openai',
  },
  'o3-mini': {
    id: 'o3-mini',
    name: 'o3 Mini',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    capabilities: { vision: false, thinking: true, tools: true },
    ownedBy: 'openai',
  },
  'chatgpt-4o-latest': {
    id: 'chatgpt-4o-latest',
    name: 'ChatGPT-4o Latest',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'openai',
  },
};
