import type { CatalogModelSpec } from './types';

export const OPENSOURCE_MODELS: Record<string, CatalogModelSpec> = {
  // Meta Llama
  'llama-3.3-70b-instruct': {
    id: 'llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'meta',
  },
  'llama-3.1-405b-instruct': {
    id: 'llama-3.1-405b-instruct',
    name: 'Llama 3.1 405B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'meta',
  },
  'llama-3.1-70b-instruct': {
    id: 'llama-3.1-70b-instruct',
    name: 'Llama 3.1 70B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'meta',
  },
  'llama-3.1-8b-instruct': {
    id: 'llama-3.1-8b-instruct',
    name: 'Llama 3.1 8B',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'meta',
  },
  'llama-3.2-11b-vision-instruct': {
    id: 'llama-3.2-11b-vision-instruct',
    name: 'Llama 3.2 11B Vision',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'meta',
  },
  'llama-3.2-90b-vision-instruct': {
    id: 'llama-3.2-90b-vision-instruct',
    name: 'Llama 3.2 90B Vision',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'meta',
  },

  // Mistral
  'mistral-large-latest': {
    id: 'mistral-large-latest',
    name: 'Mistral Large',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'mistral',
  },
  'pixtral-large-latest': {
    id: 'pixtral-large-latest',
    name: 'Pixtral Large',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'mistral',
  },
  'codestral-latest': {
    id: 'codestral-latest',
    name: 'Codestral',
    contextWindow: 256_000,
    maxOutputTokens: 4_096,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'mistral',
  },

  // xAI Grok
  'grok-4.6': {
    id: 'grok-4.6',
    name: 'Grok 4.6',
    contextWindow: 500_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-build-0.1': {
    id: 'grok-build-0.1',
    name: 'Grok Build 0.1',
    contextWindow: 256_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: false, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-4.5': {
    id: 'grok-4.5',
    name: 'Grok 4.5',
    contextWindow: 500_000,
    maxOutputTokens: 16_384,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-4.3': {
    id: 'grok-4.3',
    name: 'Grok 4.3',
    contextWindow: 1_000_000,
    maxOutputTokens: 16_384,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-4.20-0309-reasoning': {
    id: 'grok-4.20-0309-reasoning',
    name: 'Grok 4.20 Reasoning',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: false, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-4.20-0309-non-reasoning': {
    id: 'grok-4.20-0309-non-reasoning',
    name: 'Grok 4.20 Non-Reasoning',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: false, thinking: false, tools: true },
    ownedBy: 'xai',
  },
  'grok-4.20-multi-agent-0309': {
    id: 'grok-4.20-multi-agent-0309',
    name: 'Grok 4.20 Multi-Agent',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: false, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-420-reasoning': {
    id: 'grok-420-reasoning',
    name: 'Grok 420 Reasoning',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: false, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-4': {
    id: 'grok-4',
    name: 'Grok 4',
    contextWindow: 500_000,
    maxOutputTokens: 32_768,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-3': {
    id: 'grok-3',
    name: 'Grok 3 (Retired)',
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    capabilities: { vision: true, thinking: true, tools: true },
    ownedBy: 'xai',
  },
  'grok-2': {
    id: 'grok-2',
    name: 'Grok 2',
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'xai',
  },
  'grok-2-vision-1212': {
    id: 'grok-2-vision-1212',
    name: 'Grok 2 Vision (1212)',
    contextWindow: 32_768,
    maxOutputTokens: 8_192,
    capabilities: { vision: true, thinking: false, tools: true },
    ownedBy: 'xai',
  },
};
