/** Matches inline arithmetic/relational operations (e.g. 1 + 2, x = 3) without false-matching hyphenated words. */
const INLINE_MATH_OPERATOR_REGEX = /(?:^|[^A-Za-z])(?:\d+\s*[=+\-*/<>]\s*\d+|[A-Za-z]\s*[=+\-*/<>]\s*[A-Za-z0-9])/;

/** Matches characteristic LaTeX syntax characters (backslash, superscript, subscript, braces). */
const INLINE_MATH_MARKER_REGEX = /[\\^_{}]/;

/** Matches an entire string wrapped in a single live artifact fenced code block (HTML or interaction JSON). */
const SINGLE_LIVE_ARTIFACT_FENCE_REGEX =
  /^```(amc-live-artifact-html|amc-live-artifact-interaction)\n([\s\S]*?)\n?```\s*$/;

export const extractSingleLiveArtifactFence = (content: string): { language: string; code: string } | null => {
  const match = content.trim().match(SINGLE_LIVE_ARTIFACT_FENCE_REGEX);
  if (!match) {
    return null;
  }

  return {
    language: match[1],
    code: match[2] ?? '',
  };
};

const isLikelyMathExpression = (value: string): boolean => {
  const trimmedValue = value.trim();

  if (!trimmedValue) {
    return false;
  }

  return (
    INLINE_MATH_MARKER_REGEX.test(trimmedValue) ||
    INLINE_MATH_OPERATOR_REGEX.test(trimmedValue) ||
    trimmedValue.includes('\n')
  );
};

/**
 * Normalizes backslash-escaped LaTeX math delimiters (e.g. `\$$...$$` or `\$...$`)
 * generated by some models back to standard markdown math delimiters when the
 * enclosed content resembles actual mathematical expressions.
 */
export const normalizeEscapedMathDelimiters = (value: string): string => {
  let nextValue = value.replace(/\\\$\$([\s\S]+?)\\\$\$/g, (match, innerContent: string) =>
    isLikelyMathExpression(innerContent) ? `$$${innerContent}$$` : match,
  );

  nextValue = nextValue.replace(/\\\$((?:\\.|[^\\$])+?)\\\$/g, (match, innerContent: string) =>
    isLikelyMathExpression(innerContent) ? `$${innerContent}$` : match,
  );

  return nextValue;
};
